/** Opt in against backend/tests/central_remote_app.py, never a live GPU. */
import { expect, test } from "@playwright/test";
import { API_BASE_URL, getFeatures, getStyles } from "../lib/api";

test.skip(process.env.CENTRAL_REMOTE_TESTS !== "1", "Requires the isolated synthetic remote harness");

test("actual shared client discovers the central remote catalogs without style leakage", async () => {
  const features = await getFeatures();
  expect(features.map((feature) => feature.id)).toEqual(["hairstyle", "makeup", "nails"]);
  const catalogs = await Promise.all(features.map((feature) => getStyles(feature.id)));
  const ids = catalogs.map((styles) => styles.map((style) => style.id));
  expect(ids[0]).toContain("crew_cut");
  expect(ids[1]).toContain("soft_glam");
  expect(ids[2]).toContain("classic_red");
  for (let index = 0; index < ids.length; index++) {
    for (let other = index + 1; other < ids.length; other++) {
      expect(ids[index].filter((id) => ids[other].includes(id))).toEqual([]);
    }
  }
});

for (const { feature, pagePath, styleId, styleName, button, resultAlt, inferencePath } of [
  { feature: "hairstyle", pagePath: "/", styleId: "crew_cut", styleName: "Crew Cut", button: "Generate preview", resultAlt: "Hairstyle generated by the project trained model" },
  { feature: "makeup", pagePath: "/makeup", styleId: "soft_glam", styleName: "Soft Glam", button: "Generate makeup", resultAlt: "MAKEUP-001 generated Soft Glam result" },
  ...[
    ["classic_red", "Classic Red Gloss", "model"], ["glossy_black", "Glossy Black", "model"],
    ["nude_pink", "Nude Pink Gloss", "renderer"], ["french_tip", "French Tip", "renderer"],
    ["pink_ombre", "Pink Ombre", "renderer"],
  ].map(([styleId, styleName, inferencePath]) => ({ feature: "nails", pagePath: "/nails", styleId, styleName,
    inferencePath, button: "Try this style", resultAlt: `Hand with ${styleName} nails` })),
]) {
  test(`${feature}/${styleId} traverses page, client, API, handler and synthetic inference boundaries`, async ({ page, request }) => {
    const crashes: string[] = [];
    const requests: string[] = [];
    page.on("pageerror", (error) => crashes.push(error.message));
    page.on("request", (request) => requests.push(new URL(request.url()).pathname));
    const styles = page.waitForResponse((response) => new URL(response.url()).pathname === `/features/${feature}/styles`);
    await page.goto(pagePath);
    expect((await styles).status()).toBe(200);
    const image = await request.get(`${API_BASE_URL}/_test/image`);
    expect(image.status()).toBe(200);
    await page.locator("input[type=file]").setInputFiles({ name: "synthetic.png", mimeType: "image/png", buffer: await image.body() });
    await page.locator("button[aria-pressed]").filter({ hasText: styleName }).click();
    const generated = page.waitForResponse((response) => new URL(response.url()).pathname === `/features/${feature}/generate`);
    await page.getByRole("button", { name: button }).click();
    const response = await generated;
    expect(response.status()).toBe(200);
    const result = await response.json();
    expect(result.status).toBe("completed");
    expect(result.style.id).toBe(styleId);
    expect(result.metadata.feature).toBe(feature);
    if (feature === "nails") {
      expect(result.generator).toBe("nails_hybrid");
      expect(result.metadata.inference_path).toBe(inferencePath);
      expect(result.metadata.nails_edited).toBe(5);
      expect(result.metadata.timing_seconds).toHaveProperty("mask_refinement");
    }
    await expect(page.getByAltText(resultAlt)).toBeVisible();
    expect(crashes).toEqual([]);
    expect(requests.filter((url) => ["/styles", "/generate", "/makeup/styles", "/makeup/generate", "/nails/styles", "/nails/generate"].includes(url))).toEqual([]);
  });
}
