import { expect, test } from "@playwright/test";
import fs from "node:fs";
import path from "node:path";

const image = fs.readFileSync(path.join(__dirname, "fixtures", "portrait.png"));
const dataUrl = `data:image/png;base64,${image.toString("base64")}`;
const cases = [
  { feature: "hairstyle", page: "/", style: "Crew Cut", id: "crew_cut", action: "Generate preview", original: "Original uploaded portrait", generated: "Hairstyle generated by the project trained model" },
  { feature: "makeup", page: "/makeup", style: "Soft Glam", id: "soft_glam", action: "Generate makeup", original: "Original uploaded portrait", generated: "MAKEUP-001 generated Soft Glam result" },
  { feature: "nails", page: "/nails", style: "Classic Red Gloss", id: "classic_red", action: "Try this style", original: "Original hand photo", generated: "Hand with Classic Red Gloss nails" },
] as const;

for (const item of cases) {
  test(`${item.feature} shows processing then opens a reusable comparison dialog`, async ({ page }) => {
    let generations = 0;
    await page.route("**/health", (route) => route.fulfill({ json: { status: "ok", generator: "remote_flux" } }));
    await page.route(`**/features/${item.feature}/styles`, (route) => route.fulfill({ json: [
      { id: item.id, name: item.style, description: "A test look", status: item.feature === "makeup" ? "trained_preset" : "experimental" },
    ] }));
    await page.route(`**/features/${item.feature}/generate`, async (route) => {
      generations++;
      expect(route.request().method()).toBe("POST");
      expect(route.request().postData()).toContain(item.id);
      await new Promise((resolve) => setTimeout(resolve, 400));
      await route.fulfill({ json: {
        status: "completed", generator: item.feature === "makeup" ? "flux2_klein_base_makeup001" : "remote_flux",
        style: { id: item.id, name: item.style, description: "A test look", status: "experimental" },
        image: { data_url: dataUrl, content_type: "image/png", width: 128, height: 128 },
      } });
    });
    await page.goto(item.page);
    await expect(page.locator("button[aria-pressed]")).toHaveCount(1);
    await page.locator("input[type=file]").setInputFiles({ name: "portrait.png", mimeType: "image/png", buffer: image });
    await page.locator("button[aria-pressed]").click();
    await page.getByRole("button", { name: item.action }).click();
    await expect(page.locator(".studio-processing")).toBeVisible();
    await expect(page.locator(".studio-processing")).toContainText("Time elapsed");
    const dialog = page.getByRole("dialog");
    await expect(dialog).toBeVisible();
    await expect(dialog.getByAltText(item.original)).toBeVisible();
    await expect(dialog.getByAltText(item.generated)).toBeVisible();
    await expect(dialog.getByText("01 / ORIGINAL IMAGE")).toBeVisible();
    await expect(dialog.getByText("02 / GENERATED IMAGE")).toBeVisible();
    await expect(dialog.getByRole("link", { name: /Download image/ })).toHaveAttribute("download", `andreas-${item.id}.png`);
    const download = page.waitForEvent("download");
    await dialog.getByRole("link", { name: /Download image/ }).click();
    expect((await download).suggestedFilename()).toBe(`andreas-${item.id}.png`);
    await dialog.getByRole("button", { name: "Close", exact: true }).click();
    await expect(dialog).not.toBeVisible();
    await page.getByRole("button", { name: "View your result again" }).click();
    await expect(dialog).toBeVisible();
    await dialog.getByRole("button", { name: "Regenerate" }).click();
    await expect(dialog).toBeVisible();
    expect(generations).toBe(2);
  });
}

test("mobile comparison can close with Escape without horizontal overflow", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.route("**/health", (route) => route.fulfill({ json: { status: "ok", generator: "remote_flux" } }));
  await page.route("**/features/hairstyle/styles", (route) => route.fulfill({ json: [
    { id: "crew_cut", name: "Crew Cut", description: "Short", status: "experimental" },
  ] }));
  await page.route("**/features/hairstyle/generate", (route) => route.fulfill({ json: {
    status: "completed", generator: "remote_flux", style: { id: "crew_cut", name: "Crew Cut", description: "Short", status: "experimental" },
    image: { data_url: dataUrl, content_type: "image/png", width: 128, height: 128 },
  } }));
  await page.goto("/");
  await page.locator("input[type=file]").setInputFiles({ name: "portrait.png", mimeType: "image/png", buffer: image });
  await page.locator("button[aria-pressed]").click();
  await page.getByRole("button", { name: "Generate preview" }).click();
  await expect(page.getByRole("dialog")).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.keyboard.press("Escape");
  await expect(page.getByRole("dialog")).not.toBeVisible();
});

test("generation failure removes processing and keeps the page ready to retry", async ({ page }) => {
  await page.route("**/health", (route) => route.fulfill({ json: { status: "ok", generator: "remote_flux" } }));
  await page.route("**/features/hairstyle/styles", (route) => route.fulfill({ json: [
    { id: "crew_cut", name: "Crew Cut", description: "Short", status: "experimental" },
  ] }));
  await page.route("**/features/hairstyle/generate", async (route) => {
    await new Promise((resolve) => setTimeout(resolve, 200));
    await route.fulfill({ status: 502, json: { detail: "The inference service is unavailable." } });
  });
  await page.goto("/");
  await page.locator("input[type=file]").setInputFiles({ name: "portrait.png", mimeType: "image/png", buffer: image });
  await page.locator("button[aria-pressed]").click();
  await page.getByRole("button", { name: "Generate preview" }).click();
  await expect(page.locator(".studio-processing")).toBeVisible();
  await expect(page.getByRole("alert").filter({ hasText: "The inference service is unavailable." })).toBeVisible();
  await expect(page.locator(".studio-processing")).not.toBeVisible();
  await expect(page.getByRole("button", { name: "Generate preview" })).toBeEnabled();
  await expect(page.getByRole("dialog")).toHaveCount(0);
});
